Repository zuri-training/Proj-T_C_Gen-Team-74, pull requests merged in 2022-08, with the labels that each got.

#44 File generation handler
  quickterms/settings.py
  requirements.txt
  tc_site/admin.py
  tc_site/forms/GenDocumentForm.py
  tc_site/migrations/0001_initial.py
  tc_site/migrations/0002_documentmodel.py
  tc_site/models.py
  tc_site/models/CompanyModel.py
  tc_site/models/DocumentModel.py
  tc_site/models/GenDocumentModel.py
  tc_site/static/doc_templates/privacy_policy/blog_PP_temp.md
  tc_site/static/doc_templates/privacy_policy/ecommerce_PP_temp.md
  tc_site/static/doc_templates/privacy_policy/mobile_app_PP_temp.md
  tc_site/static/doc_templates/privacy_policy/privacy_policy_template.md
  tc_site/static/doc_templates/privacy_policy/small_biz_PP_temp.md
  tc_site/static/doc_templates/terms_and_conditions/T&C_temp.md
  tc_site/static/doc_templates/terms_and_conditions/ecommerce_T&C_temp.md
  tc_site/static/doc_templates/terms_and_conditions/mobile_app_T&C_temp.md
  tc_site/static/doc_templates/terms_and_conditions/saas_T&C_temp.md
  tc_site/static/doc_templates/terms_and_conditions/small_biz_T&C_temp.md
  tc_site/static/doc_templates/terms_and_conditions/test_template.txt
  tc_site/static/documents/small_biz_PP_temp_ASk5Xj9.md
  tc_site/static/js/form.js
  tc_site/templates/tc_site/pages/form.html
  tc_site/view_helpers/gen_file_helper.py
  tc_site/view_helpers/gen_form_helper.py
Labels: Backend

#43 Wellington
  requirements.txt
  tc_site/static/css/auth/log-in.css
  tc_site/static/css/auth/sign-up.css
  tc_site/static/js/modals.js
  tc_site/templates/tc_site/blocks/auth/log-in.html
  tc_site/templates/tc_site/blocks/auth/sign-up.html
  tc_site/templates/tc_site/blocks/auth/signin.html
  tc_site/templates/tc_site/blocks/auth/signup.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/pages/base.html
  tc_site/templates/tc_site/pages/landing.html
Labels: Frontend

#48 Authenticating views
  tc_site/forms/signinForm.py
  tc_site/forms/signupForm.py
  tc_site/migrations/0003_remove_documentmodel_document_type_and_more.py
  tc_site/static/css/auth/log-in.css
  tc_site/static/js/modals.js
  tc_site/templates/tc_site/blocks/auth/sign-up.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/pages/base.html
  tc_site/view_helpers/landing_helper.py
  tc_site/view_helpers/signin_helper.py
  tc_site/view_helpers/signup_helper.py
Labels: enhancement, Backend

#58 Linked all authentication views with the authentication pages
  tc_site/forms/signinForm.py
  tc_site/forms/signupForm.py
  tc_site/migrations/0004_alter_documentmodel_document.py
  tc_site/models/CompanyModel.py
  tc_site/models/DocumentModel.py
  tc_site/static/css/auth/log-in.css
  tc_site/static/css/auth/sign-up.css
  tc_site/static/css/main.css
  tc_site/static/js/modals.js
  tc_site/templates/tc_site/blocks/auth/log-in.html
  tc_site/templates/tc_site/blocks/auth/sign-up.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/pages/base.html
  tc_site/urls.py
  tc_site/view_helpers/gen_file_helper.py
  tc_site/view_helpers/gen_form_helper.py
  tc_site/view_helpers/landing_helper.py
  tc_site/view_helpers/signin_helper.py
  tc_site/view_helpers/signout_helper.py
  tc_site/view_helpers/signup_helper.py
  tc_site/views.py
Labels: Frontend, Backend

#40 Revert "Dinho"
  tc_site/static/css/landing/dinho.css
  tc_site/static/css/style.css
  tc_site/static/js/main.js
  tc_site/templates/tc_site/blocks/landing/main-section-1.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
Labels: bug, Frontend

#62 Fixed Form Stepper bug
  tc_site/static/css/form/form.css
  tc_site/static/css/landing/taiwo.css
  tc_site/templates/tc_site/blocks/landing/main-section-4.html
  tc_site/templates/tc_site/blocks/landing/main-section-5.html
  tc_site/templates/tc_site/blocks/landing/main-section-6.html
  tc_site/templates/tc_site/blocks/landing/main-section-7.html
  tc_site/templates/tc_site/blocks/layout/landing/footer.html
  tc_site/templates/tc_site/pages/base.html
Labels: bug, Frontend

#60 html and css code for landing page
  html code and css landing page/block pages/main-section-4.html
  html code and css landing page/block pages/main-section-5.html
  html code and css landing page/block pages/main-section-6.html
  html code and css landing page/block pages/main-section-7.html
  html code and css landing page/css/taiwo.css
  html code and css landing page/layout/footer.html
Labels: bug, Frontend

#68 Fixed all the styling bugs on the landing page, implemented a new nav
  tc_site/static/assets/landing/hero/hero-bg.png
  tc_site/static/assets/landing/navbar/Vector.png
  tc_site/static/assets/landing/navbar/uickTerms.png
  tc_site/static/css/landing/dinho.css
  tc_site/static/css/landing/hero.css
  tc_site/static/css/landing/taiwo.css
  tc_site/static/css/layout/landing/navbar.css
  tc_site/static/css/main.css
  tc_site/static/js/main.js
  tc_site/static/js/modals.js
  tc_site/templates/tc_site/blocks/landing/contact.html
  tc_site/templates/tc_site/blocks/landing/faq.html
  tc_site/templates/tc_site/blocks/landing/hero.html
  tc_site/templates/tc_site/blocks/landing/main-section-1.html
  tc_site/templates/tc_site/blocks/landing/main-section-3.html
  tc_site/templates/tc_site/blocks/landing/main-section-4.html
  tc_site/templates/tc_site/blocks/landing/main-section-5.html
  tc_site/templates/tc_site/blocks/landing/main-section-6.html
  tc_site/templates/tc_site/blocks/landing/main-section-7.html
  tc_site/templates/tc_site/blocks/layout/landing/footer.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/pages/base.html
Labels: bug, enhancement, Frontend

#59 add coming soon page
  tc_site/templates/tc_site/blocks/coming_soon.html
Labels: Frontend

#71 Wellington 1
  tc_site/static/css/auth/log-in.css
  tc_site/static/css/auth/sign-up.css
  tc_site/templates/tc_site/blocks/auth/log-in.html
  tc_site/templates/tc_site/blocks/auth/sign-up.html
Labels: bug, Frontend

#74 hero fixed
  tc_site/static/css/landing/hero.css
  tc_site/static/css/landing/taiwo.css
  tc_site/static/js/form.js
  tc_site/templates/tc_site/blocks/landing/hero.html
  tc_site/templates/tc_site/blocks/landing/main-section-1.html
  tc_site/templates/tc_site/blocks/landing/main-section-2.html
  tc_site/templates/tc_site/blocks/landing/main-section-7.html
  tc_site/templates/tc_site/pages/landing/base.html
Labels: bug, Frontend

#77 Embed view complete
  tc_site/static/js/embed.js
  tc_site/templates/tc_site/blocks/generated/generated.html
  tc_site/templates/tc_site/blocks/landing/main-section-2.html
Labels: Frontend

#79 Ogunkapc: export view handler
  requirements.txt
  tc_site/view_helpers/export_helper.py
Labels: Backend

#73 forgotten password link fully functional
  quickterms/settings.py
  quickterms/urls.py
  tc_site/templates/tc_site/pages/password_reset.html
  tc_site/templates/tc_site/pages/password_reset_complete.html
  tc_site/templates/tc_site/pages/password_reset_confirm.html
  tc_site/templates/tc_site/pages/password_reset_done.html
  tc_site/templates/tc_site/pages/password_reset_email.html
  tc_site/urls.py
Labels: enhancement, Backend

#80 html and css code for dashboard layouts (side&nav)
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/archive.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/contact.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/dashboard.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/gendocs.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/generate.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/home.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/logout.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/notifications.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/person.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/person1.png
  dashboard layout/tc_site/static/assets/dashboard/layout/taiwo/quickterms.png
  dashboard layout/tc_site/static/css/dashboard/taiwo.css
  dashboard layout/tc_site/templates/tc_site/blocks/layout/dashboard/archive.html
  dashboard layout/tc_site/templates/tc_site/blocks/layout/dashboard/dashboard.html
  dashboard layout/tc_site/templates/tc_site/blocks/layout/dashboard/gendocs.html
  dashboard layout/tc_site/templates/tc_site/blocks/layout/dashboard/generate.html
Labels: enhancement, Frontend

#88 Sticky navbar implemented
  tc_site/static/assets/dashboard/layout/archive.png
  tc_site/static/assets/dashboard/layout/contact.png
  tc_site/static/assets/dashboard/layout/dashboard.png
  tc_site/static/assets/dashboard/layout/gendocs.png
  tc_site/static/assets/dashboard/layout/generate.png
  tc_site/static/assets/dashboard/layout/home.png
  tc_site/static/assets/dashboard/layout/logout.png
  tc_site/static/assets/dashboard/layout/notifications.png
  tc_site/static/assets/dashboard/layout/person.png
  tc_site/static/assets/dashboard/layout/person1.png
  tc_site/static/assets/dashboard/layout/quickterms.png
  tc_site/static/css/layout/dashboard/taiwo.css
  tc_site/static/css/layout/landing/navbar.css
  tc_site/static/js/navbar.js
  tc_site/templates/tc_site/blocks/auth/sign-up.html
  tc_site/templates/tc_site/blocks/layout/dashboard/dashboard.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/pages/landing/base.html
Labels: enhancement, Frontend

#89 Hero new design done
  tc_site/static/css/landing/hero.css
  tc_site/templates/tc_site/blocks/landing/hero.html
  tc_site/templates/tc_site/pages/landing/base.html
Labels: enhancement, Frontend

#90 navbar fixes
  tc_site/static/css/landing/hero.css
  tc_site/static/css/layout/landing/navbar.css
  tc_site/static/js/navbar.js
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/view_helpers/landing_helper.py
Labels: bug, enhancement, Frontend

#91 dasboard layout fixed
  tc_site/static/assets/dashboard/layout/sidenav/logo.png
  tc_site/static/assets/dashboard/layout/taiwo/archive.png
  tc_site/static/assets/dashboard/layout/taiwo/contact.png
  tc_site/static/assets/dashboard/layout/taiwo/dashboard.png
  tc_site/static/assets/dashboard/layout/taiwo/gendocs.png
  tc_site/static/assets/dashboard/layout/taiwo/generate.png
  tc_site/static/assets/dashboard/layout/taiwo/home.png
  tc_site/static/assets/dashboard/layout/taiwo/logout.png
  tc_site/static/assets/dashboard/layout/taiwo/notifications.png
  tc_site/static/assets/dashboard/layout/taiwo/person.png
  tc_site/static/assets/dashboard/layout/taiwo/person1.png
  tc_site/static/assets/dashboard/layout/taiwo/quickterms.png
  tc_site/static/css/dashboard/dinho.css
  tc_site/static/css/dashboard/taiwo.css
  tc_site/static/css/layout/dashboard/main.css
  tc_site/static/js/dinho.js
  tc_site/templates/tc_site/blocks/layout/dashboard/dashboard.html
  tc_site/templates/tc_site/blocks/layout/dashboard/left_sidebar.html
  tc_site/templates/tc_site/blocks/layout/dashboard/top_navbar.html
  tc_site/templates/tc_site/pages/dashboard/base.html
Labels: bug, enhancement, Frontend

#92 separated dashboard layout styles and logic from the dashboard block
  tc_site/static/css/dashboard/dinho.css
  tc_site/static/css/layout/dashboard/main.css
  tc_site/static/css/layout/landing/navbar.css
  tc_site/static/js/dashboard/navbar.js
  tc_site/static/js/dinho.js
  tc_site/templates/tc_site/blocks/layout/dashboard/left_sidebar.html
  tc_site/templates/tc_site/pages/dashboard/base.html
Labels: enhancement, Frontend

#93 changed the background image on a section of the landing page and sty…
  quickterms/settings.py
  tc_site/static/assets/landing/victor/Group 118.png
  tc_site/static/css/landing/dinho.css
  tc_site/static/css/landing/victor.css
  tc_site/templates/tc_site/blocks/landing/main-section-1.html
  tc_site/templates/tc_site/pages/landing/base.html
Labels: enhancement, Frontend

#95 Minor fixes to landing 2nd section
  tc_site/static/css/landing/faq.css
  tc_site/static/css/landing/taiwo.css
  tc_site/static/css/landing/victor.css
  tc_site/static/css/layout/dashboard/main.css
  tc_site/static/js/dashboard/navbar.js
  tc_site/static/js/faq.js
  tc_site/static/js/navbar.js
  tc_site/templates/tc_site/blocks/landing/main-section-1.html
  tc_site/templates/tc_site/blocks/landing/main-section-7.html
  tc_site/templates/tc_site/blocks/layout/dashboard/top_navbar.html
  tc_site/templates/tc_site/gen-doc.html
  tc_site/templates/tc_site/gen_file.html
  tc_site/templates/tc_site/pages/dashboard/base.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/view_helpers/preview_helper.py
Labels: bug, enhancement, Frontend

#83 dashboard form and styles
  tc_site/static/css/dashboard/gen-docs.css
  tc_site/templates/tc_site/blocks/dashboard/generated_docs.html
Labels: enhancement, Frontend

#94 updated the code and assets for contact and footer
  tc_site/static/assets/dashboard/layout/taiwo/archive.png
  tc_site/static/assets/dashboard/layout/taiwo/contact.png
  tc_site/static/assets/dashboard/layout/taiwo/dashboard.png
  tc_site/static/assets/dashboard/layout/taiwo/gendocs.png
  tc_site/static/assets/dashboard/layout/taiwo/generate.png
  tc_site/static/assets/dashboard/layout/taiwo/home.png
  tc_site/static/assets/dashboard/layout/taiwo/logout.png
  tc_site/static/assets/dashboard/layout/taiwo/notifications.png
  tc_site/static/assets/dashboard/layout/taiwo/person.png
  tc_site/static/assets/dashboard/layout/taiwo/profile.png
  tc_site/static/assets/dashboard/layout/taiwo/quickterms.png
  tc_site/static/assets/landing/taiwo/fb.png
  tc_site/static/assets/landing/taiwo/gps.png
  tc_site/static/assets/landing/taiwo/ig.png
  tc_site/static/assets/landing/taiwo/phone.png
  tc_site/static/assets/landing/taiwo/sms.png
  tc_site/static/assets/landing/taiwo/tt.png
  tc_site/static/css/landing/taiwo.css
  tc_site/templates/tc_site/blocks/landing/contact.html
  tc_site/templates/tc_site/blocks/layout/landing/footer.html
Labels: enhancement, Frontend

#96 Landing page and dashboard layout enhancements
  tc_site/static/assets/landing/doc-img-bubble/bubbles.png
  tc_site/static/assets/landing/preview/preview-bg.png
  tc_site/static/assets/landing/preview/preview-bg.svg
  tc_site/static/assets/landing/taiwo/howto-1.png
  tc_site/static/css/dashboard/gen-docs.css
  tc_site/static/css/landing/preview_modal.css
  tc_site/static/css/landing/taiwo.css
  tc_site/static/css/landing/victor.css
  tc_site/static/css/layout/dashboard/main.css
  tc_site/static/css/layout/landing/navbar.css
  tc_site/static/css/main.css
  tc_site/static/js/dashboard/navbar.js
  tc_site/static/js/main.js
  tc_site/static/js/modals.js
  tc_site/static/js/navbar.js
  tc_site/templates/tc_site/blocks/dashboard/dashboard.html
  tc_site/templates/tc_site/blocks/dashboard/generated_docs.html
  tc_site/templates/tc_site/blocks/landing/main-section-5.html
  tc_site/templates/tc_site/blocks/landing/main-section-6.html
  tc_site/templates/tc_site/blocks/landing/preview_template.html
  tc_site/templates/tc_site/blocks/landing/template.html
  tc_site/templates/tc_site/blocks/layout/dashboard/left_sidebar.html
  tc_site/templates/tc_site/blocks/layout/dashboard/top_navbar.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/pages/dashboard/base.html
  tc_site/templates/tc_site/pages/form.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/urls.py
  tc_site/view_helpers/dashboard/generated_docs_helper.py
  tc_site/view_helpers/preview_blank_helper.py
  tc_site/views.py
Labels: enhancement, Frontend

#97 bug fixes on dashboard navbar and added username error checking
  tc_site/static/css/layout/dashboard/main.css
  tc_site/templates/tc_site/pages/dashboard/base.html
  tc_site/view_helpers/signin_helper.py
  tc_site/view_helpers/signup_helper.py
Labels: bug

#98 updated sign up and login modals and export logic
  tc_site/static/css/auth/log-in.css
  tc_site/static/css/auth/sign-up.css
  tc_site/templates/tc_site/blocks/auth/log-in.html
  tc_site/templates/tc_site/blocks/auth/sign-up.html
  tc_site/templates/tc_site/blocks/generated/generated.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/urls.py
  tc_site/view_helpers/export_docx_helper.py
  tc_site/view_helpers/export_helper.py
  tc_site/views.py
Labels: bug, enhancement, Frontend, Backend

#99 implemented the home page of the dashboard page
  github team task/Damilola-Akinwunmi.txt
  github team task/Enomfon-Obot.txt
  github team task/JhayEchenim.txt
  github team task/Mina.txt
  github team task/Ogunka-Promise.txt
  github team task/Oladimeji-Adebiyi.txt
  github team task/Omolade-Odewunmi.txt
  github team task/Omolara-Akinbola.txt
  github team task/de-marauder.txt
  github team task/dinho.txt
  github team task/vickie.txt
  tc_site/static/css/dashboard/dinho.css
  tc_site/static/css/landing/dinho.css
  tc_site/static/js/dinho.js
  tc_site/templates/tc_site/blocks/dashboard/dashboard.html
  tc_site/templates/tc_site/pages/dashboard/dashboard.html
Labels: bug, documentation, enhancement, Frontend

#102 responsive user profile block page for dashboard
  tc_site/static/assets/dashboard/layout/taiwo/avatar.jpg
  tc_site/static/assets/dashboard/layout/taiwo/edit.png
  tc_site/static/css/dashboard/profile.css
  tc_site/templates/tc_site/blocks/dashboard/profile.html
Labels: enhancement, Frontend

#104 added password reset page
  tc_site/static/css/auth/reset-password.css
  tc_site/templates/tc_site/blocks/auth/reset-password.html
Labels: enhancement, Frontend

#111 Wellington 1
  tc_site/static/css/dashboard/archive.css
  tc_site/templates/tc_site/blocks/dashboard/archive.html
Labels: enhancement, Frontend

#101 about us page
  .vscode/settings.json
  tc_site/static/assets/landing/aboutus/aboutus.png
  tc_site/static/assets/landing/aboutus/banner.png
  tc_site/static/assets/landing/aboutus/goals.png
  tc_site/static/assets/landing/aboutus/ourteam.png
  tc_site/static/css/landing/aboutus.css
  tc_site/templates/tc_site/blocks/landing/aboutus.html
Labels: enhancement, Frontend

#125 about us mobile view
  Group 120.png
  Group 121.png
  Group 122.png
  aboutus.html
  aboutus.png
  banner.png
  goals.png
  style.css
Labels: Frontend

#131 modified forgot password page
  tc_site/static/js/modals.js
  tc_site/templates/tc_site/blocks/auth/forgot-password.html
  tc_site/templates/tc_site/blocks/auth/reset-password.html
  tc_site/templates/tc_site/pages/password_reset.html
  tc_site/templates/tc_site/pages/password_reset_confirm.html
Labels: bug, Frontend

#135 updated the heading of the contact section
  tc_site/static/css/landing/taiwo.css
  tc_site/templates/tc_site/blocks/landing/contact.html
Labels: enhancement, Frontend

#133 Update Omolade-Odewunmi.md
  Contributors/Omolade-Odewunmi.md
Labels: documentation

#139 Re implemented the about page
  aboutus.html
  style.css
  tc_site/static/assets/about/Group 120.png
  tc_site/static/assets/about/Group 121.png
  tc_site/static/assets/about/Group 122.png
  tc_site/static/assets/about/aboutus.png
  tc_site/static/assets/about/aboutus/aboutus.png
  tc_site/static/assets/about/aboutus/banner.png
  tc_site/static/assets/about/aboutus/goals.png
  tc_site/static/assets/about/aboutus/ourteam.png
  tc_site/static/assets/about/banner.png
  tc_site/static/assets/about/goals.png
  tc_site/static/css/about/about.css
  tc_site/static/css/landing/aboutus.css
  tc_site/templates/tc_site/blocks/about/about.html
  tc_site/templates/tc_site/blocks/generated/generated.html
  tc_site/templates/tc_site/blocks/landing/aboutus.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/urls.py
  tc_site/view_helpers/about_helper.py
  tc_site/view_helpers/dashboard/profile_helper.py
  tc_site/views.py
Labels: bug, enhancement, Frontend

#140 Performed style fixes and page linking
  tc_site/models/DocumentModel.py
  tc_site/static/assets/auth/cancel.png
  tc_site/static/css/about/aboutus.css
  tc_site/static/css/auth/forgot-password.css
  tc_site/static/css/auth/log-in.css
  tc_site/static/css/auth/reset-password.css
  tc_site/static/css/auth/sign-up.css
  tc_site/static/css/form/preview.css
  tc_site/static/js/modals.js
  tc_site/templates/tc_site/blocks/about/aboutus.html
  tc_site/templates/tc_site/blocks/auth/log-in.html
  tc_site/templates/tc_site/blocks/auth/reset-password.html
  tc_site/templates/tc_site/blocks/auth/sign-up.html
  tc_site/templates/tc_site/blocks/dashboard/archive.html
  tc_site/templates/tc_site/blocks/documentation.html
  tc_site/templates/tc_site/blocks/layout/dashboard/left_sidebar.html
  tc_site/templates/tc_site/blocks/layout/landing/footer.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/blocks/preview.html
  tc_site/templates/tc_site/gen_file.html
  tc_site/templates/tc_site/pages/embededpage.html
  tc_site/templates/tc_site/pages/form.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/templates/tc_site/pages/password_reset.html
  tc_site/templates/tc_site/pages/password_reset_complete.html
  tc_site/templates/tc_site/pages/password_reset_confirm.html
  tc_site/templates/tc_site/pages/password_reset_done.html
  tc_site/urls.py
  tc_site/view_helpers/about_helper.py
  tc_site/view_helpers/dashboard/archive_helper.py
  tc_site/view_helpers/dashboard/profile_helper.py
  tc_site/view_helpers/preview_helper.py
  tc_site/view_helpers/signup_helper.py
  tc_site/views.py
Labels: bug, enhancement, Frontend

#141 Removed vscode config folder
  .gitignore
  .vscode/settings.json
  tc_site/static/assets/landing/hero/hero.png
Labels: invalid

#149 implemented save as draft and linked dashboard pages to the database
  tc_site/forms/GenDocumentForm.py
  tc_site/migrations/0007_documentmodel_document_state.py
  tc_site/migrations/0008_alter_documentmodel_company.py
  tc_site/migrations/0009_alter_companymodel_company_email_and_more.py
  tc_site/models/CompanyModel.py
  tc_site/models/DocumentModel.py
  tc_site/static/assets/auth/1724830a-aba1-4710-ac7f-365431b447ac
  tc_site/static/css/layout/dashboard/main.css
  tc_site/templates/tc_site/blocks/dashboard/archive.html
  tc_site/templates/tc_site/blocks/dashboard/dashboard.html
  tc_site/templates/tc_site/blocks/dashboard/generated_docs.html
  tc_site/templates/tc_site/blocks/layout/dashboard/top_navbar.html
  tc_site/templates/tc_site/blocks/preview.html
  tc_site/templates/tc_site/gen-doc.html
  tc_site/templates/tc_site/gen_file.html
  tc_site/templates/tc_site/pages/dashboard/base.html
  tc_site/templates/tc_site/pages/form.html
  tc_site/view_helpers/dashboard/archive_helper.py
  tc_site/view_helpers/dashboard/dashboard_helper.py
  tc_site/view_helpers/dashboard/generated_docs_helper.py
  tc_site/view_helpers/dashboard/profile_helper.py
  tc_site/view_helpers/gen_form_helper.py
  tc_site/view_helpers/preview_helper.py
Labels: bug, enhancement, Frontend, Backend

#148 fixed archive style bug
  tc_site/static/css/dashboard/archive.css
Labels: bug, enhancement, Frontend

#147 updated the dashboard profile code
  tc_site/static/css/dashboard/profile.css
  tc_site/templates/tc_site/blocks/dashboard/profile.html
Labels: bug, enhancement, Frontend

#150 replaced sqlite3 with postgresql
  quickterms/settings.py
  tc_site/migrations/0002_companymodel_app_name_and_more.py
  tc_site/migrations/0002_documentmodel.py
  tc_site/migrations/0003_remove_documentmodel_document_type_and_more.py
  tc_site/migrations/0004_alter_documentmodel_document.py
  tc_site/migrations/0005_companymodel_app_name.py
  tc_site/migrations/0006_rename_document_documentmodel_content_and_more.py
  tc_site/migrations/0007_documentmodel_document_state.py
  tc_site/migrations/0008_alter_documentmodel_company.py
  tc_site/migrations/0009_alter_companymodel_company_email_and_more.py
  tc_site/static/assets/dashboard/gen-docs/doc.png
  tc_site/static/css/dashboard/gen-docs.css
  tc_site/static/css/form/form.css
  tc_site/static/js/dashboard/navbar.js
  tc_site/static/js/dinho.js
  tc_site/templates/tc_site/blocks/dashboard/archive.html
  tc_site/templates/tc_site/blocks/dashboard/dashboard.html
  tc_site/templates/tc_site/blocks/dashboard/generated_docs.html
  tc_site/templates/tc_site/blocks/dashboard/profile.html
  tc_site/templates/tc_site/blocks/landing/hero.html
  tc_site/templates/tc_site/blocks/landing/main-section-5.html
  tc_site/templates/tc_site/blocks/layout/dashboard/left_sidebar.html
  tc_site/templates/tc_site/blocks/layout/landing/footer.html
  tc_site/templates/tc_site/blocks/layout/landing/navbar.html
  tc_site/templates/tc_site/gen-doc.html
  tc_site/templates/tc_site/gen_file.html
  tc_site/templates/tc_site/pages/dashboard/base.html
  tc_site/templates/tc_site/pages/form.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/templates/tc_site/pages/password_reset_complete.html
  tc_site/templates/tc_site/pages/password_reset_confirm.html
  tc_site/templates/tc_site/pages/password_reset_done.html
  tc_site/urls.py
  tc_site/view_helpers/dashboard/archive_helper.py
  tc_site/view_helpers/dashboard/profile_helper.py
  tc_site/view_helpers/gen_form_helper.py
  tc_site/view_helpers/signin_helper.py
  tc_site/view_helpers/signup_helper.py
  tc_site/views.py
Labels: enhancement, Backend, Deployment

#151 added functionality for save and edit document later
  quickterms/settings.py
  tc_site/migrations/0002_companymodel_app_name_and_more.py
  tc_site/models/DocumentModel.py
  tc_site/static/css/auth/forgot-password.css
  tc_site/static/css/dashboard/archive.css
  tc_site/templates/tc_site/blocks/auth/log-in.html
  tc_site/templates/tc_site/blocks/auth/sign-up.html
  tc_site/templates/tc_site/blocks/dashboard/archive.html
  tc_site/templates/tc_site/blocks/dashboard/index.html
  tc_site/templates/tc_site/gen-doc.html
  tc_site/templates/tc_site/gen_file.html
  tc_site/templates/tc_site/pages/dashboard/base.html
  tc_site/templates/tc_site/pages/form.html
  tc_site/urls.py
  tc_site/view_helpers/dashboard/dashboard_helper.py
  tc_site/view_helpers/dashboard/generated_docs_helper.py
  tc_site/view_helpers/delete_company_helper.py
  tc_site/view_helpers/delete_doc_helper.py
  tc_site/view_helpers/gen_form_helper.py
  tc_site/view_helpers/preview_helper.py
  tc_site/view_helpers/signin_helper.py
  tc_site/views.py
Labels: bug, enhancement, Frontend, Backend

#152 created feedback modal
  tc_site/static/css/review.css
  tc_site/templates/tc_site/blocks/review.html
Labels: enhancement, Frontend

#153 Front end for feeback section added
  tc_site/static/css/generated/generated.css
  tc_site/static/css/review.css
  tc_site/static/js/review.js
  tc_site/templates/tc_site/blocks/dashboard/generated_docs.html
  tc_site/templates/tc_site/blocks/generated/generated.html
  tc_site/templates/tc_site/blocks/review.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/templates/tc_site/pages/password_reset.html
  tc_site/templates/tc_site/pages/password_reset_confirm.html
Labels: enhancement, Frontend

#154 feedback functionality added
  tc_site/admin.py
  tc_site/migrations/0003_feedbackmodel.py
  tc_site/models/FeedBackModel.py
  tc_site/static/css/landing/taiwo.css
  tc_site/static/css/review.css
  tc_site/static/js/review.js
  tc_site/templates/tc_site/blocks/dashboard/archive.html
  tc_site/templates/tc_site/blocks/generated/generated.html
  tc_site/templates/tc_site/blocks/review.html
  tc_site/templates/tc_site/pages/landing/base.html
  tc_site/urls.py
  tc_site/view_helpers/dashboard/archive_helper.py
  tc_site/view_helpers/dashboard/dashboard_helper.py
  tc_site/view_helpers/feedback_helper.py
  tc_site/views.py
Labels: enhancement, Backend

#155 fixed reset password page error
  tc_site/templates/tc_site/pages/password_reset_confirm.html
Labels: bug

#156 fixed reset password page error
  tc_site/templates/tc_site/pages/password_reset_confirm.html
Labels: bug
